version: '3'

services:
  api:
    build: backend_api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./backend_api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: web_client
    command: ["npm", "start"]
    volumes:
      - ./web_client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules:
